FROM node:18.20-alpine AS builder

ENV PNPM_HOME="/pnpm"

ENV PATH="$PATH_HOME:$PATH"

ENV TIME_ZONE="Asia/Shanghai"

WORKDIR /usr/src/app

COPY ./ /usr/src/app

RUN npm config set registry https://registry.npmmirror.com/

RUN npm install -g pnpm && pnpm install --frozen-lockfile

CMD pnpm build