FROM node:18.20-alpine AS builder

ENV PNPM_HOME="/pnpm"

ENV PATH="$PATH_HOME:$PATH"

WORKDIR /usr/src/app

COPY ./ /usr/src/app

RUN npm config set registry https://registry.npmmirror.com/

RUN npm install -g pnpm && pnpm install --frozen-lockfile

RUN pnpm build

FROM nginx:1.27.0-alpine-slim

COPY --from=builder /usr/src/app/etc /etc

COPY --from=builder /usr/src/app/dist .

EXPOSE 80
